services:
  - type: web
    name: lumina-ai
    env: python
    buildCommand: cd lumina_ai && pip install -r requirements.txt && cd backend && python manage.py collectstatic --no-input && python manage.py migrate
    startCommand: cd lumina_ai/backend && gunicorn lumina.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: 'False'
      - key: RENDER_EXTERNAL_HOSTNAME
        sync: false
